name: Build and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Update Package Index
        run: sudo apt-get update

      - name: Install Boost
        run: sudo apt-get install -y libboost-all-dev

      - name: Install OpenCV
        run: sudo apt-get install -y libopencv-dev

      - name: Install WebSocket++
        run: |
          git clone --branch 0.8.2 https://github.com/zaphoyd/websocketpp.git
          sudo cp -r ./websocketpp/websocketpp ./include

      - name: Build project
        run: make

  test:
    needs: build

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: make test_ALL
